image_path: "before/images/train"
label_path: "before/labels/train"
background_path: "coco128/images/train2017"
output_path: "output"
target_instances_per_class: 500
min_instances: 2
max_instances: 10
width: 960
height: 768
min_scale: 0.5
max_scale: 5.0
val_ratio: 0.2   # -1 denotes don't split
use_tqdm: 1      #  1 denotes use tqdm